services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: gms-cloud-timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: gms_backend
      POSTGRES_USER: gms
      POSTGRES_PASSWORD: gms
    ports:
      - "5432:5432" # Optional: expose if you want to connect with pgAdmin
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gms -d gms_backend" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  cloud_broker:
    image: eclipse-mosquitto:2.0
    container_name: gms-cloud-broker
    command:
      - /bin/sh
      - -c
      - >
        printf 'listener 1883\nallow_anonymous true\nlistener 9001\nprotocol websockets\nallow_anonymous true\npersistence true\npersistence_location /mosquitto/data/\nlog_dest file /mosquitto/log/mosquitto.log\n' > /tmp/mosquitto.conf && exec mosquitto -c /tmp/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - cloud_broker_data:/mosquitto/data
      - cloud_broker_log:/mosquitto/log
    restart: unless-stopped

  backend:
    image: maxnoragami/gms-backend:latest
    container_name: gms-cloud-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/gms_backend
      SPRING_DATASOURCE_USERNAME: gms
      SPRING_DATASOURCE_PASSWORD: gms
      GMS_TAILSCALE_API_KEY: ${GMS_TAILSCALE_API_KEY}
      GMS_TAILSCALE_TAILNET: ${GMS_TAILSCALE_TAILNET}
      GMS_MQTT_TLS_CA_CERT_PATH: ""
      GMS_MQTT_TLS_CLIENT_CERT_PATH: ""
      GMS_MQTT_TLS_KEY_PASSWORD: ""
      GMS_PUBLIC_MQTT_HOST: ${GMS_PUBLIC_MQTT_HOST:-<your-mqtt-broker-host>}
      GMS_CORS_ALLOWED_ORIGINS: ${GMS_CORS_ALLOWED_ORIGINS:-}
      JAVA_TOOL_OPTIONS: "--add-opens=java.base/java.net=ALL-UNNAMED"
    command: --gms.mqtt.broker-url=tcp://cloud_broker:1883
    depends_on:
      timescaledb:
        condition: service_healthy
      cloud_broker:
        condition: service_started
    restart: unless-stopped


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: gms-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

  mqttx_web:
    image: emqx/mqttx-web:latest
    container_name: gms-mqttx-web
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  timescaledb_data:
  cloud_broker_data:
  cloud_broker_log:
